CREATE TABLE ns_v2.casb_file_local
(
    `ns_tenant_id` UInt32 CODEC(DoubleDelta, LZ4),
    `id` String CODEC(ZSTD(1)),
    `ns_insertion_epoch_timestamp` DateTime CODEC(DoubleDelta, LZ4),
    `created` DateTime64(6),
    `app` LowCardinality(String),
    `appcategory` LowCardinality(String),
    `appsuite` LowCardinality(String),
    `classification_label` String CODEC(ZSTD(1)),
    `classification_labels` String CODEC(ZSTD(1)),
    `classification_object_labels` Array(String) CODEC(ZSTD(1)),
    `classification_object_value_ids` Array(String) CODEC(ZSTD(1)),
    `classification_object_value_texts` Array(String) CODEC(ZSTD(1)),
    `classification_object_vendor_apps` Array(String) CODEC(ZSTD(1)),
    `classification_object_vendor_instances` Array(String) CODEC(ZSTD(1)),
    `classification_vendor` String CODEC(ZSTD(1)),
    `instance` LowCardinality(String),
    `content_hash` String CODEC(ZSTD(1)),
    `mime_type` LowCardinality(String),
    `timestamp` DateTime64(6),
    `last_scanned` DateTime64(6),
    `parent_id` String CODEC(ZSTD(1)),
    `parent_type` LowCardinality(String),
    `owner_id` String CODEC(ZSTD(1)),
    `owner_email` String CODEC(ZSTD(1)),
    `owner_display_name` String CODEC(ZSTD(1)),
    `last_modifier_id` String CODEC(ZSTD(1)),
    `last_modifier_email` String CODEC(ZSTD(1)),
    `url` String CODEC(ZSTD(1)),
    `path` String CODEC(ZSTD(1)),
    `name` String CODEC(ZSTD(1)),
    `size` UInt64,
    `geo` String CODEC(ZSTD(1)),
    `exposure` LowCardinality(String),
    `media_type_category` String CODEC(ZSTD(1)),
    `content_classification_dlp_rule` Array(String) CODEC(ZSTD(1)),
    `content_classification_dlp_hitCount` Array(UInt64),
    `content_classification_dlp_severity` Array(String) CODEC(ZSTD(1)),
    `content_classification_dlp_profiles` Array(Array(String)) CODEC(ZSTD(1)),
    `content_classification_entity_data_types` Array(Array(String)) CODEC(ZSTD(1)),
    `content_classification_entity_sensitivity_levels` Array(Array(String)) CODEC(ZSTD(1)),
    `content_classification_entity_counts` Array(Array(UInt32)),
    `content_classification_status` String CODEC(ZSTD(1)),
    `content_classification_hash` String CODEC(ZSTD(1)),
    `file_root_id` String CODEC(ZSTD(1)),
    `file_root_type` String CODEC(ZSTD(1)),
    `access_inheritance_type` String CODEC(ZSTD(1)),
    `legacy_id` String CODEC(ZSTD(1)),
    `access_sources_id` Array(String) CODEC(ZSTD(1)),
    `access_sources_type` Array(String) CODEC(ZSTD(1)),
    `exemption_policies` Array(String) CODEC(ZSTD(1)),
    `exemption_end` DateTime64(3),
    `ns_updated` DateTime64(6),
    `ns_cdc_timestamp` DateTime64(3),
    `ns_deleted` UInt8,
    `ns_meta` UInt16 DEFAULT 0,
    INDEX idx_casb_file_id id TYPE bloom_filter GRANULARITY 1,
    INDEX idx_casb_file_timestamp timestamp TYPE minmax GRANULARITY 8,
    INDEX idx_casb_file_its ns_insertion_epoch_timestamp TYPE minmax GRANULARITY 8,
    INDEX idx_casb_file_file_root_id file_root_id TYPE bloom_filter GRANULARITY 1
)
ENGINE = ReplicatedReplacingMergeTree('/clickhouse/tables/{cluster}-{shard}/ns_v2.casb_file_local', '{replica}', ns_cdc_timestamp)
PARTITION BY ns_tenant_id % 10
PRIMARY KEY (ns_tenant_id, instance, app)
ORDER BY (ns_tenant_id, instance, app, id)
SETTINGS min_bytes_for_wide_part = 10000000, min_rows_for_wide_part = 100000, index_granularity = 8192
